# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_remove_map_content_map'),
        ('maps', '0030_auto_20180320_1119'),
    ]

    operations = [
    ]
